# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a42af6298ab5615b110c5bdea5629bba032f081dbd210654821140dad926f3905b429bd174fa36e79176694e4711fad0e669728b6d049c16a94d58595ad9a32a

test:
  secret_key_base: 0972d0727b2a0f1f520c9994785fe3f38751e9d13aa7ddabb926f3fe66d69887b447518f83c8dd05e484923a84a1014de88d25c55cc4da92447825a852753507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
